Flizpay/flizpay-for-woocommerce

- public/js/flizpay-public.js
- Nonce param was outside of the request body
> fix: place nonce inside data in ajax request

- includes/class-flizpay-gateway.php
- Use transient to store cashback data for 5 minutes instead of requesting from api on every instanciation
> feat: use transient for cashback data

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
- Fix Readme translation and links
- Upgrade plugin version to 1.0.1
> fix: translations and links

- includes/class-flizpay-gateway.php
- Before we were applying the cashback discount as a flat number to the whole purchase value. This would make it not possible for woocommerce to distinguish between the real value paid for each item, making it troublesome to apply correct refund values. 
- Applied cashback to each item of the purchase, including shipping fees so they can be refunded later.
> fix: apply cashback discount on each item of the cart

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
> release: v1.1.0

- public/class-flizpay-public.php
- public/js/flizpay-public.js
Improve readability and add cancel button
> feat: add cancel button to loading wheel

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
> release: 1.4.2

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
> release: v1.4.4

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
Hotfix order total amount being calculated incorrectly
> release: v1.4.5

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
Hotfix to include the files on SVN
> release: bump to version 2.0.1

- public/css/flizpay-public.css
- Fix the font size of the checkout button to prevent wrapping
> fix: the font size of the checkout button

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
- Release v2.0.3
- Dont calculate taxes during express-checkout if already included in shipping
- Make sure no shipping is previously included when creating express-checkout order
> Release v2.0.3

- includes/class-flizpay-activator.php
- includes/class-flizpay-deactivator.php
- API was imported incorrectly on activator and deactivator
- Make sure settings exist before attempt to deactivate and activate
---
> fix: api path on activator and deactivator

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
> release: v2.0.4

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
> release: bump version to 2.0.6

- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- includes/class-flizpay.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
- public/js/flizpay-globals.js
- Fix german translation on loading wheel 
- Adjust changelog for better readability
- Remove redundancy on payment method name `FLIZpay plugin` to `FLIZpay`
---
> release: 2.0.7

- includes/class-flizpay-api-service.php
- Products in transaction was removed on the classes decoupling refactoring. Re adding it
---
> fix: add products to transaction

- public/css/flizpay-public.css
- public/js/flizpay-express-checkout.js
> feat: remove google fonts

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
> release: bump version to v2.2.0

- CHANGELOG.txt
- README.txt
- admin/js/flizpay-admin.js
- flizpay.php
- includes/class-flizpay-gateway.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
- Added missing variable delcarations and wait on admin page before trying to access loaded elements
---
---
---
> hotfix: declare variables and admin timeout

- CHANGELOG.txt
- README.txt
- flizpay.php
- includes/class-flizpay-gateway.php
- languages/flizpay-for-woocommerce-de_DE.po
- languages/flizpay-for-woocommerce-en_GB.po
- languages/flizpay-for-woocommerce-en_US.po
> release: v2.4.4
